package kawaiicatalogitem;

import org.eclipse.jface.dialogs.Dialog;
import org.eclipse.swt.SWT;
import org.eclipse.swt.layout.GridData;
import org.eclipse.swt.layout.GridLayout;
import org.eclipse.swt.widgets.Composite;
import org.eclipse.swt.widgets.Control;
import org.eclipse.swt.widgets.Label;
import org.eclipse.swt.widgets.Shell;
import org.eclipse.swt.widgets.Text;



public class CustomDialog extends Dialog {
	// private:- only same class access
	
	private Text skuText;
	private String skuValue;
	
	/*
	 * we have to preserve parent's behaviour while we customize the function
	 * Same method name
	 * Bigger method = your hook
     * Smaller method = framework core logic
     * Override when you want to customise.
     * Call super when you want to keep the framework alive.
	 */
	
	//by receiving shell reference in constructor it knows which parent window it belongs to
	//reference points to the actual shell object
	public CustomDialog (Shell parentShell) {
	
		super (parentShell);
	/*super(parentShell) passes the parent window to the Dialog part of your 
	 *object so the dialog knows who it belongs to.
	*/
	// “Call the constructor of my parent class (Dialog) and pass parentShell to it.”
	// since CustomDialog IS-A Dialog --> Dialog cannot exist without knowing which Shell is its parent
	}
	
	@Override

	protected void configureShell (Shell shell) {
		// protected -> accessible to subclasses
		/*
		 * This Shell is the dialog’s own shell
		   JFace internally creates a new shell for the dialog
		   Then it calls: configureShell(dialogShell)
		 */
		super.configureShell(shell);
		//Call Dialog’s version of configureShell()
		// configureShell() --> builds contents
		// the opens dialog
		shell.setText("Kawaii Catalog – Search"); // puchna hai bhaiya se
		
	}
	
	@Override
	// Control --> returning some UI thing
	// Composite = a container that can hold other controls
	/*
	   A dialog has a shell (Shell → top-level container)
       Inside the shell → composites (Composite → inner container)
       Inside composites → labels, text fields, buttons
	 */
	protected Control createDialogArea (Composite parent) {
		/*
		 * Dialog already knows how to build a dialog safely (not creating from scratch)
		 * super.createDialogArea() creates the base container
		 * parent is the inner container generated by Dialog for attaching UI elements (customizing) to standard Dialog container
		 * rest all used in 65 customizes the standard dialog
		 * 
		 * 
		 * Below we have longer version of 70th line of code.
		 * Control temp = super.createDialogArea(parent);
		   Composite container = (Composite) temp;
		   
		   Control is like superclass of composite.so, to make function general it returns control .
		   Casting only changes how you are allowed to talk to object.
		   
		   super.createDialogArea(parent) creates the default dialog container, returns it as a Control, and we cast it to Composite so we can set a layout and add UI elements to it.
		 */
		Composite container = (Composite) super.createDialogArea(parent);
		container.setLayout(new GridLayout (2, false));
		
		Label label = new Label (container, SWT.NONE);
		label.setText("SKU:");
		
		skuText = new Text (container, SWT.BORDER);
		skuText.setLayoutData(new GridData(SWT.FILL, SWT.CENTER, true, false));
		
		skuText.setMessage("Search by SKU");
		
		
		//Dialog expects container returned from this function
		// here container is control as its boundary of funtion. inside function its a composite
		return container;
	}
	
	@Override
	protected void okPressed() {
		skuValue = skuText.getText().trim();
		/*
		 * okpressed():
		 * captures (saves data before ui vanishing)
		 * finalizes the result
		 * ends dialog lifecycle
		 * closes dialog
		 * give the control back to main window
		 */
		super.okPressed();
	}
	
	// public since kawaiicatalog needs it
	public String getSkuValue() {
		return skuValue;
	}
}